services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: football
      POSTGRES_PASSWORD: matawan123
      POSTGRES_DB: football
    ports:
      - "5433:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - db

  app:
    image: docker.io/souerta/football-nice-apis:latest
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/football
      SPRING_DATASOURCE_USERNAME: football
      SPRING_DATASOURCE_PASSWORD: matawan123
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: