services:

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: football
      POSTGRES_PASSWORD: matawan123
      POSTGRES_DB: football
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: